### PR TITLE
Remove dependency on ipaddr.js

### PR DESCRIPTION
**Pull request by jbt**
Parses addresses directly into an array (typed `Uint8Array` if available for speeeeeeed).

I'd like to add a couple more tests to make sure parsing is absolutely correct and wonderful, but if `net.isIP` says the address is valid then I think this should just work fine.

I'm also trying to figure out if there's any way to use the `uv_inet_pton` that `net.isIP` uses internally (in iojs at least) because that does all the parsing work anyway so it's silly to duplicate the work. Don't know whether that's possible though.

### CODE REVIEW

**Comment by jbt** [comment]
For some reason this seems to pull perf right down in the benchmark. Need to see if there's anything specific I've done that's slowing it down

**Comment by simontabor** [comment]
Oh that's interesting, I thought ipaddr.js was pretty inefficient with the way it does expensive regex matches... ah well I love benchmarks

**Comment by jbt** [comment]
Yeah I think I've tried to be too clever with my Array / Uint8Array stuff. Just changing https://github.com/gosquared/ipcheck/blob/a55dfc4bbf1126a9f84518080a580c56906d6e04/ipcheck.js#L38 to `self.address = [ blah ]` speeds it up 50x (waaa)

**Comment by jbt** [comment]
Yeeeees that's much better. All told this PR now gives anywhere from 2-8x perf improve over before, for IPs it actually has to parse (i.e. all the non-invalid benchmarks)

**Pull request merged**
